### ISSUE TITLE
Does this work for React.Component?

### ISSUE THREAD

**Issue by svenadlung** [nayaabkhan/react-polyglot#17]
@nayaabkhan Thank you so much for this project. Really appreciate your work. 

Following the sample code everything works well with pure functions but whenever I try to use it with a class extending React.Component, it fails to access `t`. It should be available with `this.props.t`, shouldn't it?

```
...
import { translate } from 'react-polyglot'
...
export class MyComponent extends Component {
   render() {
      console.log(this.props.t('test')
   }
}
...
export default translate()(MyComponent)
```

Any idea why the translate function (`t`) is not injected to the props?

**Comment by nayaabkhan** [comment]
Hello @svenadlung! Thanks for the appreciating words 😄 

Yes, it doesn't matter whether you access `t` inside a Class or a Function component. It should work regardless. I've created a Sandbox with a minimal example and it is working well: https://codesandbox.io/s/mq76ojk228?fontsize=14.

I see you've exported your component twice– first as a named export (`export class...`) and then as a default export. Be sure that you're importing the default one as that is the one which is wrapped by `translate()`.

```js
// this is the one that has `t` injected by the `translate` function.
import MyComponent from './my-component'

// this won't have `t` injected.
import { MyComponent } from './my-component'
```

**Comment by svenadlung** [comment]
@nayaabkhan Oh no, what a pity! I didn't noticed I exported the class before. Now everything works as expected. Thank you so much. So sorry wasting your time.

**Comment by nayaabkhan** [comment]
No problem, happy to help. 😄
