### ISSUE TITLE
Pass node-polyglot options as props

### ISSUE THREAD

**Issue by ghost** [nayaabkhan/react-polyglot#31]
Hey!

I'm using this in a project and so far it works great! :)

But `<I18n>` does not seem to accept additional options for `node-polyglot`.
For example there is no way to configure `allowMissing` and `onMissingKey`.

I think we should be apple to pass options as props, or maybe pass an object to be forwarded to `node-polyglot`?

```
<I18n allowMissing onMissingKey={() => console.log('Missing key')}>
```
or
```
<I18n options={{ allowMissing: true, onMissingKey: () => console.log('Missing key') }}>
```

What do you think?

Thanks!

**Comment by nayaabkhan** [comment]
Hey @simonunlikely! It is always great to hear from the users, especially if it is working well. Thanks for the kind words.

This would be a great addition for sure. Assigning it to myself for further development. Thanks for the proposal. :bowing_man:

**Comment by soda0289** [comment]
@simonunlikely The newest release 0.6.0 has support for options such as `onMissingKey`. Hope that helps.

**Comment by ghost** [comment]
Hey!

Thanks for the work guys, will test this asap :)

Cheers 🍾

**Comment by nayaabkhan** [comment]
@simonunlikely Will be closing this issue. I hope your test went well. 😄
