### ISSUE TITLE
Npm install won't install the lib folder

### ISSUE THREAD

**Issue by rouflak** [nayaabkhan/react-polyglot#4]
When I run the `npm install --save react-polyglot` command, it correctly installs the node module folder but the `lib` folder is missing in the directory.

I think it is due to the `prepublish` script. Maybe something has gone wrong with it.

Thx

**Comment by ToniChaz** [comment]
I have the same problem

**Comment by guillaumearm** [comment]
waiting, you can add a postinstall script in your package.json : 
`
cd node_modules/react-polyglot ; npm run build
`

**Comment by nayaabkhan** [comment]
Hey guys, checking it out. Thanks for the hints!

**Comment by nayaabkhan** [comment]
Fixed in cc5a95adcb691770785954748bcae2dc9ce46519.
