### ISSUE TITLE
react-polygot: Warning: Missing translation for key: '...' 

### ISSUE THREAD

**Issue by Ghadir31** [nayaabkhan/react-polyglot#61]
Hello, I keep on getting warnings regarding my keys. I followed the setup exactly as done by the following project: 

https://github.com/mikeludemann/react-international/tree/957980e5c504eefb8b419cd090ec911a187ad929/public

(Meaning I have my translations inside a translation folder inside public folder).

I get these errors by default after I clone the above repo, do and npm install and an npm start. There are warnings in the console even though everything is working as it's supposed. Is there a way to disable these warnings? 

Thank you for the great pacakge

**Comment by nayaabkhan** [comment]
Hi @Ghadir31! I'm glad you found the package useful.

About the issue you're facing: It would help me pin down the problem if you can push a test repository where we can observe this issue.

**Comment by medjabir** [comment]
@Ghadir31 If you have your js lang files in place with keys and their corresponding translations, you'll need to delete your browser's cache or maybe try a quick access from an incognito tab.
If your js translation file doesn't have the key you want to translate, It throws out this error. 

@nayaabkhan Is there a parameter we can pass in to hide these warnings, something like allowMissing: true ?

**Comment by nayaabkhan** [comment]
Yes it's possible, check the props at [`src/i18n.js`](https://github.com/nayaabkhan/react-polyglot/blob/master/src/i18n.js#L10).

**Comment by medjabir** [comment]
Thank you @nayaabkhan and thank you very much for the package

**Comment by nayaabkhan** [comment]
Closing this for the lack of activity.
